# Generated by Django 4.2.11 on 2024-03-25 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_deadline_alter_todo_finished_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
    ]
